export const CREATE_ISSUE = 'CREATE_ISSUE';


export const GET_ZIPCODE_DETAILS="GET_ZIPCODE_DETAILS";
export const GET_ZIPCODE_DETAILS_SUCCESS = 'GET_ZIPCODE_DETAILS_SUCCESS';
export const GET_ZIPCODE_DETAILS_ERROR = 'GET_ZIPCODE_DETAILS_ERROR';
